# Generated by Django 5.1.4 on 2024-12-31 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0003_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='paciente',
        ),
        migrations.CreateModel(
            name='MedicamenteXPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
    ]
