# Generated by Django 5.1.4 on 2024-12-31 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0004_remove_medicamento_paciente_medicamentexpaciente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicamenteXPaciente',
            new_name='MedicamentoXPaciente',
        ),
    ]
