# Generated by Django 5.1.4 on 2024-12-31 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0006_alter_consulta_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
